apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app-gateway
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "time.ralf.com.ng"
    - "date.ralf.com.ng"
    - "ip.ralf.com.ng"
    - "app.ralf.com.ng"
