name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [date-service, time-service, ip-service, frontend-service]

    steps:
    - uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Image
      run: |
        IMAGE=rafel0/${{ matrix.service }}:${{ github.sha }}
        echo "IMAGE=$IMAGE"
        docker build -t $IMAGE -f ${{ matrix.service }}/Dockerfile ./${{ matrix.service }}
        # docker build -t $IMAGE ./$(matrix.service)
        docker push $IMAGE
        # Update correct manifest in k8s folder
        sed -i "s|image:.*|image: $IMAGE|" k8s/${{ matrix.service }}-deployment.yaml

    - name: Commit updated manifests
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add k8s/${{ matrix.service }}-deployment.yaml
        git commit -m "Update image for ${{ matrix.service }}-service"
        git push
